FROM node:20

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install

# Install additional tools
RUN npm install -g @nestjs/cli

# Install PM2
RUN npm install pm2 -g

# Copy application source code
COPY . .

# Copy SSL certificates
COPY ./ssl ./ssl

# RUN mkdir -p /usr/src/app/uploads
# RUN chmod -R 777 /usr/src/app/uploads

# # set server-main-node as owner of the app directory
# RUN chown -R node:node /usr/src/app/uploads

# USER node

# Expose the application port
EXPOSE 3120

# Command to start the application in development mode
CMD ["npm", "run", "start:dev"]
